import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Image from "next/image";

import { api } from "@/utils/api";
import { Button } from "@/components/ui/button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Nipost App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed left-0 right-0 top-0 z-20 flex items-center justify-center bg-white py-4">
        <div className="relative z-20 h-[80px] w-[290px]">
          <Image
            src="/NIPOST-Logo.png?v=1"
            alt="Nipost"
            fill
            className="object-contain"
          />
        </div>
      </div>
      <main className="relative flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="absolute inset-0 opacity-25">
          <Image src="/hero.jpg?v=3" alt="" fill className="object-cover" />
        </div>
        <div className="relative z-20 w-full max-w-2xl space-y-2 text-center text-white">
          <h1 className="2xl font-black md:text-4xl">
            Regulatory Compliance Tracking &amp; Enforcement Monitoring
          </h1>

          <Button variant={"destructive"} asChild size={"lg"}>
            <Link href={"/auth"}>Login or Sign Up</Link>
          </Button>
        </div>
      </main>
    </>
  );
};

export default Home;
